Message: "Parameter YAL Global"

Group1:
  Message: "Parameter YAML Local G1"
  talker:
    Message: "Parameter YAML Private G1"

Group2:
  Message: "Parameter YAML Local G2"
  talker:
    Message: "Parameter YAML Private G2"
